---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj-1-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/ryanj-1-gateway-gitops
